name: myenv3
channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - jupyterlab
  - matplotlib
  - metpy
  - netcdf4
  - numpy
  - pandas
  - pip
  - pywavelets
  - scikit-learn
  - scipy=1.6.3
  - statsmodels
  - xarray
  - basemap
  - basemap-highres
  - cartopy
  - pip:
    - pyct
    - pycwt
    - sklearn
    - wavelets
