name: myenv3
channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - jupyterlab
  - matplotlib
  - metpy
  - netcdf4
  - numpy
  - pandas
  - pip
  - scikit-learn
  - scipy
  - statsmodels
  - xarray
  - pip:
    - pycwt
