name: myenv3
channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - jupyterlab
  - matplotlib
  - metpy
  - netcdf4
  - numpy
  - pandas
  - pip
  - pywavelets=1.1.1=py37h902c9e0_3
  - scikit-learn=0.24.2=py37h18a542f_0
  - scipy=1.6.3=py37h29e03ee_0
  - statsmodels=0.12.2=py37h902c9e0_0
  - xarray=0.16.2=pyhd8ed1ab_0
  - pip:
    - pyct==0.4.8
    - pycwt==0.3.0a22
    - sklearn==0.0
    - wavelets==0.1
